/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:353e2c12-e97e-4bb7-8c13-3db312ed6ee2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_pouZ95mMs",
    "aws_user_pools_web_client_id": "43o1vcobap421vous0qj1a26c6",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "DataHawkAPI",
            "endpoint": "https://wx8dhbbjx0.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
